---

- hosts: all
  become: true
  tasks:
  
  - name: Copy sshd config to ssh config dir
    tags: sshd
    copy:
      src: "{{ sshd_template }}"
      dest: /etc/ssh/sshd_config
      owner: root
      group: "{{ sshd_usergroup }}"
      mode: 0644
    register: sshd_service

  - name: Restart sshd
    tags: sshd
    service:
      name: sshd
      state: restarted
    when: sshd_service.changed

  - name: Copy bashrc to aldoushxle home dir
    tags: bashrc
    copy:
      src: "{{ bashrc_template }}"
      dest: /home/aldoushxle/.bashrc
      owner: aldoushxle
      group: aldoushxle
      mode: 0644

  - name: Copy bash_profile to aldoushxle home dir
    tags: bashrc
    copy:
      src: "{{ bashrc_template }}"
      dest: /home/aldoushxle/.bash_profile
      owner: aldoushxle
      group: aldoushxle
      mode: 0644

  - name: Create /mnt/HxlENet_Files_NFS directory
    file:
      path: /mnt/HxlENet_Files_NFS
      state: directory
      mode: "u=rwx,g=rx,o=rx"

  - name: Mount /mnt/HxlENet_Files_NFS in /etc/fstab
    tags: mount_nfs
    blockinfile:
      path: /etc/fstab
      block: |
        # HxlENet-FreeNAS Files NFS Mount during startup
        hxlenet-freenas:/mnt/hxlenet-volume/hxlenet-files       /mnt/HxlENet_Files_NFS  nfs     rw	0      0
      
- hosts: freebsd_systems
  become: true
  tasks:

  - name: PKG upgrade pkg (FreeBSD)
    tags: pkg-upgrade
    pkgng:
      name: pkg
      state: latest
    when: ansible_distribution == "FreeBSD"

  - name: Install essential software (FreeBSD)
    pkgng:
      name: 
        - nano
        - bash
        - net-snmp
        - screen
        - neofetch
      state: latest
      
  - name: change user aldoushxle's shell to bash
    become: yes
    user:
      name: aldoushxle
      shell: /usr/local/bin/bash
        
  - name: Copy snmpd configuration file to snmp config directory
    tags: net-snmpd
    copy:
      src: net-snmpd.cfg
      dest: "{{ snmpd_config_path }}"
      owner: root
      group: wheel
      mode: 0644

- hosts: epel_systems
  become: true
  tasks:

  - name: Enable EPEL-Release Repo (EPEL)
    yum:
      name:
        - epel-release
      update_cache: yes
      state: latest

  - name: Install essential software (EPEL)
    yum:
      name: 
        - nano
        - net-snmp
        - nfs-utils
        - screen
        - neofetch
      update_cache: yes
      state: latest

  - name: Copy snmpd configuration file to snmp config directory
    tags: net-snmpd
    copy:
      src: net-snmpd.cfg
      dest: "{{ snmpd_config_path }}"
      owner: root
      group: root
      mode: 0644
            
- hosts: debian_systems
  become: true
  tasks:

  - name: Install essential software (Debian)
    apt:
      name: 
        - nano
        - snmpd
        - nfs-common
        - screen
        - neofetch
      update_cache: yes
      state: latest

  - name: Copy snmpd configuration file to snmp config directory
    tags: net-snmpd
    copy:
      src: net-snmpd.cfg
      dest: "{{ snmpd_config_path }}"
      owner: root
      group: root
      mode: 0644

  - name: Stop systemd-resolved service
    tags: fixdns
    ansible.builtin.systemd:
      name: systemd-resolved
      state: stopped
      enabled: no
    when: ansible_distribution == "Ubuntu"

  - name: Delete /etc/resolv.conf symlink
    tags: fixdns
    file:
      state: absent
      path: /etc/resolv.conf
    when: ansible_distribution == "Ubuntu"

  - name: Restart NetworkManager service
    tags: fixdns
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted
    when: ansible_distribution == "Ubuntu"
      
- hosts: fedora_systems
  become: true
  tasks:

  - name: Install essential software (Fedora)
    dnf:
      name: 
        - nano
        - net-snmp
        - wget
        - git
        - nfs-utils
        - yt-dlp
        - screen
        - neofetch
      update_cache: yes
      state: latest

  - name: Copy snmpd configuration file to snmp config directory
    tags: net-snmpd
    copy:
      src: net-snmpd.cfg
      dest: "{{ snmpd_config_path }}"
      owner: root
      group: root
      mode: 0644

  - name: Stop systemd-resolved service
    tags: fixdns
    ansible.builtin.systemd:
      name: systemd-resolved
      state: stopped
      enabled: no
    when: ansible_distribution == "Fedora"

  - name: Delete /etc/resolv.conf symlink
    tags: fixdns
    file:
      state: absent
      path: /etc/resolv.conf
    when: ansible_distribution == "Fedora"

  - name: Restart NetworkManager service
    tags: fixdns
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted
    when: ansible_distribution == "Fedora"