---

- hosts: all
  become: true
  tasks:
  
  - name: Copy sshd config to ssh config dir
    tags: sshd
    copy:
      src: "{{ sshd_template }}"
      dest: /etc/ssh/sshd_config
      owner: root
      group: "{{ sshd_usergroup }}"
      mode: 0644
    register: sshd_service

  - name: Restart sshd
    tags: sshd
    service:
      name: sshd
      state: restarted
    when: sshd_service.changed

  - name: Copy bashrc to aldoushxle home dir
    tags: bashrc
    copy:
      src: "{{ bashrc_template }}"
      dest: /home/aldoushxle/.bashrc
      owner: aldoushxle
      group: aldoushxle
      mode: 0644

  - name: Copy bash_profile to aldoushxle home dir
    tags: bashrc
    copy:
      src: "{{ bashrc_template }}"
      dest: /home/aldoushxle/.bash_profile
      owner: aldoushxle
      group: aldoushxle
      mode: 0644

  - name: Create /mnt/HxlENet_Files_NFS directory
    file:
      path: /mnt/HxlENet_Files_NFS
      state: directory
      mode: "u=rwx,g=rx,o=rx"

  - name: Mount /mnt/HxlENet_Files_NFS in /etc/fstab
    tags: mount_nfs
    blockinfile:
      path: /etc/fstab
      block: |
        # HxlENet-FreeNAS Files NFS Mount during startup
        hxlenet-freenas:/mnt/hxlenet-volume/hxlenet-files       /mnt/HxlENet_Files_NFS  nfs     rw	0      0
      
- hosts: freebsd_systems
  become: true
  tasks:

  - name: Upgrade PKG package manager (FreeBSD)
    tags: pkg-upgrade
    pkgng:
      name: pkg
      state: latest

  - name: Install essential software (FreeBSD)
    pkgng:
      name: 
        - nano
        - bash
        - net-snmp
        - screen
        - neofetch
      state: latest
      
  - name: Change user aldoushxle's shell to bash
    become: true
    user:
      name: aldoushxle
      shell: /usr/local/bin/bash
        
  - name: Copy snmpd configuration file to snmp config directory
    tags: net-snmpd
    copy:
      src: net-snmpd.cfg
      dest: "{{ snmpd_config_path }}"
      owner: root
      group: wheel
      mode: 0644

  - name: Start snmpd daemon at startup (FreeBSD)
    tags: net-snmpd
    blockinfile:
      path: /etc/rc.conf
      block: |
        # Net-SNMP service parameters
        snmpd_enable="true"
        snmpd_flags="-a"
        snmpd_conffile="/usr/local/share/snmp/snmpd.conf"
        snmptrapd_enable="true"
        snmptrapd_flags="-a -p /var/run/snmptrapd.pid"
        NET_SNMP_SYS_CONTACT="aldoushxle@gmail.com"
        NET_SNMP_SYS_LOCATION="HxlENet - Storage Closet - Virtual Machine"
        DEFAULT_SNMP_VERSION=2c
        NET_SNMP_MIB_MODULES="host smux mibII/mta_sendmail ucd-snmp/diskio"
        NET_SNMP_LOGFILE=/var/log/snmpd.log
        NET_SNMP_PERSISTENTDIR=/var/net-snmp
  
  - name: Start snmpd service
    tags: net-snmpd
    service:
      name: snmpd
      state: started

- hosts: epel_systems
  become: true
  tasks:

  - name: Enable EPEL-Release Repo (EPEL)
    yum:
      name:
        - epel-release
      update_cache: true
      state: latest

  - name: Install essential software (EPEL)
    yum:
      name: 
        - nano
        - net-snmp
        - nfs-utils
        - screen
        - neofetch
      update_cache: true
      state: latest

  - name: Copy snmpd configuration file to snmp config directory
    tags: net-snmpd
    copy:
      src: net-snmpd.cfg
      dest: "{{ snmpd_config_path }}"
      owner: root
      group: root
      mode: 0644
  
  - name: Start and activate snmpd service
    tags: net-snmpd
    ansible.builtin.systemd:
      name: snmpd
      state: started
      enabled: true

  - name: Stop firewalld service
    tags: disablefirewall
    ansible.builtin.systemd:
      name: firewalld
      state: stopped
      enabled: false

- hosts: debian_systems
  become: true
  tasks:

  - name: Install essential software (Debian/Ubuntu)
    apt:
      name: 
        - nano
        - snmpd
        - nfs-common
        - screen
        - neofetch
      update_cache: true
      state: latest

  - name: Copy snmpd configuration file to snmp config directory
    tags: net-snmpd
    copy:
      src: net-snmpd.cfg
      dest: "{{ snmpd_config_path }}"
      owner: root
      group: root
      mode: 0644

  - name: Restart and activate snmpd service
    tags: net-snmpd
    ansible.builtin.systemd:
      name: snmpd
      state: restarted
      enabled: true

  - name: Stop ufw service
    tags: disablefirewall
    ansible.builtin.systemd:
      name: ufw
      state: stopped
      enabled: false
    when: ansible_distribution == "Ubuntu"

  - name: Stop systemd-resolved service (Ubuntu)
    tags: fixdns
    ansible.builtin.systemd:
      name: systemd-resolved
      state: stopped
      enabled: false
    when: ansible_distribution == "Ubuntu"

  - name: Delete /etc/resolv.conf symlink (Ubuntu)
    tags: fixdns
    file:
      state: absent
      path: /etc/resolv.conf
    when: ansible_distribution == "Ubuntu"

  - name: Inserting DNS config to NetworkManager.conf (Ubuntu)
    tags: fixdns
    lineinfile:
      path: /etc/NetworkManager/NetworkManager.conf
      line: dns=default
      insertafter: plugins.
    when: ansible_distribution == "Ubuntu"

  - name: Restart NetworkManager service (Ubuntu)
    tags: fixdns
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted
    when: ansible_distribution == "Ubuntu"

- hosts: fedora_systems
  become: true
  tasks:

  - name: Install essential software (Fedora)
    dnf:
      name: 
        - nano
        - net-snmp
        - wget
        - git
        - nfs-utils
        - yt-dlp
        - screen
        - neofetch
      update_cache: yes
      state: latest

  - name: Copy snmpd configuration file to snmp config directory
    tags: net-snmpd
    copy:
      src: net-snmpd.cfg
      dest: "{{ snmpd_config_path }}"
      owner: root
      group: root
      mode: 0644
    
  - name: Start and activate snmpd service
    tags: net-snmpd
    ansible.builtin.systemd:
      name: snmpd
      state: started
      enabled: yes

  - name: Stop firewalld service
    tags: disablefirewall
    ansible.builtin.systemd:
      name: firewalld
      state: stopped
      enabled: false

  - name: Stop systemd-resolved service
    tags: fixdns
    ansible.builtin.systemd:
      name: systemd-resolved
      state: stopped
      enabled: false

  - name: Delete /etc/resolv.conf symlink
    tags: fixdns
    file:
      state: absent
      path: /etc/resolv.conf

  - name: Restart NetworkManager service
    tags: fixdns
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted

      


