- hosts: fedora_systems
  become: true
  roles:
    - fedora_systems

- hosts: freebsd_systems
  become: true
  roles:
    - freebsd_systems

- hosts: epel_systems
  become: true
  roles:
    - epel_servers

- hosts: debian_systems
  become: true
  roles:
    - debian_systems

- hosts: proxmox_systems
  become: true
  roles:
    - proxmox_systems
