- name: Update OS and software (SUSE)
  tags: always
  zypper: 
    name: "*"
    state: latest
    update_cache: yes
  register: system_updated

- name: Reboot systems if updated (SUSE)
  become: true
  when: system_updated.changed
  reboot: