- name: Update OS and software (Fedora)
  tags: always
  dnf: 
    name: "*"
    state: latest
    update_cache: yes
  register: system_updated

- name: Reboot systems if updated (Fedora)
  become: true
  when: system_updated.changed
  reboot:
