- name: pkg upgrade pkg (FreeBSD)
  tags: pkg-upgrade
  become: yes
  pkgng:
    name: pkg
    state: latest

- name: pkg upgrade all packages (FreeBSD)
  become: yes
  pkgng:
    name: "*"
    state: latest
  register: result_pkgs_updated

- name: Patch FreeBSD if updates are available
  tags: freebsd-update
  block:
    - name: Fetch FreeBSD OS patches
      shell:  freebsd-update --not-running-from-cron fetch
      become: yes
      register: result_fetch_successful
      changed_when: "'No updates needed' not in result_fetch_successful.stdout"

    - name: Install FreeBSD OS patches
      when: result_fetch_successful.changed
      shell:  /usr/sbin/freebsd-update install
      become: yes
      register: result_os_updated

- name: Reboot FreeBSD if updates installed
  become: yes
  when: (result_pkgs_updated.changed or result_os_updated.changed)
  reboot:
