- name: Upgrade PKG package manager (FreeBSD)
  tags: pkg-upgrade
  become: true
  pkgng:
    name: pkg
    state: latest

- name: Upgrade all installed packages (FreeBSD)
  become: true
  pkgng:
    name: "*"
    state: latest
  register: result_pkgs_updated

- name: Patch OS if updates are available (FreeBSD)
  tags: freebsd-update
  block:
    - name: Fetch OS patches (FreeBSD)
      shell:  freebsd-update --not-running-from-cron fetch
      become: true
      register: result_fetch_successful
      changed_when: "'No updates needed' not in result_fetch_successful.stdout"

    - name: Install OS patches (FreeBSD)
      when: result_fetch_successful.changed
      shell:  /usr/sbin/freebsd-update install
      become: true
      register: result_os_updated

- name: Reboot systems if updated (FreeBSD)
  become: true
  when: (result_pkgs_updated.changed or result_os_updated.changed)
  reboot:
