- name: Upgrade PKG package manager (FreeBSD)
  tags: pkg-upgrade
  become: true
  pkgng:
    name: pkg
    state: latest

- name: Upgrade all installed packages (FreeBSD)
  become: true
  pkgng:
    name: "*"
    state: latest
  register: pkgs_updated

- name: Patch OS if updates are available (FreeBSD)
  tags: freebsd-update
  block:
    - name: Fetch OS patches (FreeBSD)
      shell:  freebsd-update --not-running-from-cron fetch
      become: true
      register: fetch_successful
      changed_when: "'No updates needed' not in fetch_successful.stdout"

    - name: Install OS patches (FreeBSD)
      when: fetch_successful.changed
      shell:  /usr/sbin/freebsd-update install
      become: true
      register: os_updated

- name: Reboot systems if updated (FreeBSD)
  become: true
  when: (pkgs_updated.changed or os_updated.changed)
  reboot:
