- name: Update OS and software (EPEL)
  tags: always
  yum: 
    name: "*"
    state: latest
    update_cache: yes
  register: system_updated

- name: Reboot systems if updated (EPEL)
  become: true
  when: system_updated.changed
  reboot:
